[tool.bumpversion]
current_version = "1.2.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "package.json"
search = '"version": "{current_version}",'
replace = '"version": "{new_version}",'
